#!/bin/bash
read -p "Press any key after you've disconnected and reconnected the webcam" -n1 -s
echo ""
echo "Starting First Pass"
sudo modprobe -r uvcvideo
sudo modprobe uvcvideo
sudo systemctl restart zoneminder.service
echo "Finished First Pass"
echo "Starting Second Pass"
sudo modprobe -r uvcvideo
sudo modprobe uvcvideo
sudo systemctl restart zoneminder.service
echo "Finished Second Pass"
echo "Try it now"
