#!/usr/bin/env python

import os

official = os.popen('checkupdates').read()
official_count = official.count('\n')
aur = os.popen('yay -Qum').read()
aur_count = aur.count('\n')

singular = 'Update'
plural = singular + 's'

if official_count >= 1:
    print("Official Repos ({} {} Available)".format(official_count,singular if official_count == 1 else plural))
    print('-----------------------------------')
    print(official)
else:
    print("No updates from Official Repos\n")

if aur_count >= 1:
    print("Arch User Repository ({} {} Available)".format(aur_count,singular if aur_count == 1 else plural))
    print('-----------------------------------')
    print(aur)
else:
    print("No updates from Arch User Repository")
