#!/usr/bin/env python

import os
import sys

official = os.popen('checkupdates').read()
official_count = official.count('\n')
aur = os.popen('pikaur -Qua').read()
aur_count = aur.count('\n')

singular = 'Update'
plural = singular + 's'

if official_count == 0 and aur_count == 0:
    print("No updates from Official Repos or AUR")
    sys.exit(0)

if official_count >= 1:
    print("Official Repos ({} {} Available)".format(official_count,singular if official_count == 1 else plural))
    print('-----------------------------------')
    print(official)
else:
    print("No updates from Official Repos\n")

if aur_count >= 1:
    print("Arch User Repository ({} {} Available)".format(aur_count,singular if aur_count == 1 else plural))
    print('-----------------------------------')
    print(aur)
else:
    print("No updates from Arch User Repository")
